# Generated by Django 5.1.6 on 2025-02-21 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videoshare', '0002_alter_userprofile_interests_alter_userprofile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('subscribers_count', models.PositiveIntegerField(default=0)),
                ('videos_count', models.PositiveIntegerField(default=0)),
                ('photos_count', models.PositiveIntegerField(default=0)),
                ('interests', models.ManyToManyField(blank=True, related_name='general_user_profiles', to='videoshare.interest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
