# Generated by Django 5.1.6 on 2025-02-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('subscribers_count', models.PositiveIntegerField(default=0)),
                ('videos_count', models.PositiveIntegerField(default=0)),
                ('photos_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
